ALTER TABLE "Task" ADD COLUMN "repositoryId" INTEGER;
ALTER TABLE "Task" ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Task" ADD CONSTRAINT "Task_repositoryId_fkey"
FOREIGN KEY ("repositoryId") REFERENCES "GithubRepository"("id") ON DELETE SET NULL ON UPDATE CASCADE;
